### ISSUE TITLE
[Geschlossen] Umfrage zum Unterbau

### ISSUE THREAD

**Issue by Malternative3772** [LinuxGuides-OS/LinuxGuidesOS#10]
Welche Distro sollen wir als Unterbau nehmen? Hier die Umfrage:

[![](https://api.gh-polls.com/poll/01F3HZQWFDNEB2H8XSKVDX2YTX/Ubuntu)](https://api.gh-polls.com/poll/01F3HZQWFDNEB2H8XSKVDX2YTX/Ubuntu/vote)
[![](https://api.gh-polls.com/poll/01F3HZQWFDNEB2H8XSKVDX2YTX/Arch)](https://api.gh-polls.com/poll/01F3HZQWFDNEB2H8XSKVDX2YTX/Arch/vote)
[![](https://api.gh-polls.com/poll/01F3HZQWFDNEB2H8XSKVDX2YTX/Debian)](https://api.gh-polls.com/poll/01F3HZQWFDNEB2H8XSKVDX2YTX/Debian/vote)
[![](https://api.gh-polls.com/poll/01F3HZQWFDNEB2H8XSKVDX2YTX/RHEL)](https://api.gh-polls.com/poll/01F3HZQWFDNEB2H8XSKVDX2YTX/RHEL/vote)

**Comment by DasPrombelBread** [comment]
**Das Ergebnis der Umfrage:** 
**Ubuntu** gewinnt mit mit 17 stimmen, dicht gefolgt von Arch mit 16 Stimmen.
Somit wird es als erstes eine Ubuntu-Basierte Version geben, in Zukunft eventuell aber auch eine Arch-Basierte

**Comment by Juliaaan2502** [comment]
> 
> 
> **Das Ergebnis der Umfrage:**
> **Ubuntu** gewinnt mit mit 17 stimmen, dicht gefolgt von Arch mit 16 Stimmen.
> Somit wird es als erstes eine Ubuntu-Basierte Version geben, in Zukunft eventuell aber auch eine Arch-Basierte

Nice Nice, ne Debian 32x Based wär cool, aber vlt nich' nötig. ne Arch Basierte is auch cool.
