### ISSUE TITLE
Website von LinuxGuidesOS 👀 

### ISSUE THREAD

**Issue by Juliaaan2502** [LinuxGuides-OS/LinuxGuidesOS#17]
Hey Leute. Wir hatten vor uns einen Website Domain zu holen für LinuxGuidesOS. Nun ist die Frage... Welcher Link? Welche URL?
- Beide URLs sind verfügbar, nur wir fragen uns... welche ist am besten. Könnt ihr einmal abstimmen?
Danke :D 
------
**LinuxGuidesOS Developer Team**

[![](https://api.gh-polls.com/poll/01F3X6D9XC8ANDEX816008MY5K/https%3A%2F%2Flinuxguidesos.de%2F)](https://api.gh-polls.com/poll/01F3X6D9XC8ANDEX816008MY5K/https%3A%2F%2Flinuxguidesos.de%2F/vote)

[![](https://api.gh-polls.com/poll/01F3X6D9XC8ANDEX816008MY5K/https%3A%2F%2Flinuxguides-os.de%2F)](https://api.gh-polls.com/poll/01F3X6D9XC8ANDEX816008MY5K/https%3A%2F%2Flinuxguides-os.de%2F/vote)

**Comment by Juliaaan2502** [comment]
lol hat nicht geklappt 

[![](https://api.gh-polls.com/poll/01F3X6D9XC8ANDEX816008MY5K/https%3A%2F%2Flinuxguidesos.de%2F)](https://api.gh-polls.com/poll/01F3X6D9XC8ANDEX816008MY5K/https%3A%2F%2Flinuxguidesos.de%2F/vote)
[![](https://api.gh-polls.com/poll/01F3X6D9XC8ANDEX816008MY5K/https%3A%2F%2Flinuxguides-os.de%2F)](https://api.gh-polls.com/poll/01F3X6D9XC8ANDEX816008MY5K/https%3A%2F%2Flinuxguides-os.de%2F/vote)

**Comment by Juliaaan2502** [comment]
Irgendwie klappt die Poll API nicht... WOW

**Comment by Juliaaan2502** [comment]
/polls "https://linuxguides-os.de/" "https://linuxguidesos.de/"

**Comment by Juliaaan2502** [comment]
So hier https://strawpoll.de/45a96fy

**Comment by jjk4** [comment]
Noch eine Frage: Kostet das nicht was?

**Comment by rexjohannes** [comment]
Ja

**Comment by jjk4** [comment]
> Ja

Okay, noch eine Frage: wer bezahlt das?

**Comment by rexjohannes** [comment]
Ich

**Comment by Malternative3772** [comment]
Wir benutzen jetzt die Domain https://linuxguides-os.de
