### ISSUE TITLE
[Umfrage] Snap und Flatpak

### ISSUE THREAD

**Issue by jjk4** [LinuxGuides-OS/LinuxGuidesOS#20]
Nach aktuellem Stand soll man die Wahl haben, sich Software selbst auszusuchen oder die empfohlene Software zu installieren. 
Snap ist aber etwas umstritten, da es zu Cannonical gehört.
Soll Snap und Flatpak als Paketmanager jeweils bei der empfohlenen Software dabei sein (bei eigener Auswahl natürlich abwählbar) oder nicht (bei eigener Auswahl auswählbar)?
Bitte beim entsprechenden Kommentar mit:
- Daumen hoch (in empfohlener Software enthalten)
- Daumen runter (in empfohlener Software nicht enthalten)

reagieren.

**Comment by jjk4** [comment]
Snap

**Comment by jjk4** [comment]
Flatpak

**Comment by Juliaaan2502** [comment]
Und für einige Software vllt. mein Mirror verwenden? Also Debian Pakete

**Comment by rexjohannes** [comment]
Nur APT
