### ISSUE TITLE
[Geschlossen] Umfrage zu dem DE

### ISSUE THREAD

**Issue by Malternative3772** [LinuxGuides-OS/LinuxGuidesOS#9]
Welches Desktop Environment sollen wir nehmen. Hier kommt die Umfrage:

[![](https://api.gh-polls.com/poll/01F3HZDJ47K8FVJ126QTTXMGHD/KDE)](https://api.gh-polls.com/poll/01F3HZDJ47K8FVJ126QTTXMGHD/KDE/vote)
[![](https://api.gh-polls.com/poll/01F3HZDJ47K8FVJ126QTTXMGHD/GNOME)](https://api.gh-polls.com/poll/01F3HZDJ47K8FVJ126QTTXMGHD/GNOME/vote)
[![](https://api.gh-polls.com/poll/01F3HZDJ47K8FVJ126QTTXMGHD/XFCE)](https://api.gh-polls.com/poll/01F3HZDJ47K8FVJ126QTTXMGHD/XFCE/vote)
[![](https://api.gh-polls.com/poll/01F3HZDJ47K8FVJ126QTTXMGHD/LXQT)](https://api.gh-polls.com/poll/01F3HZDJ47K8FVJ126QTTXMGHD/LXQT/vote)
[![](https://api.gh-polls.com/poll/01F3HZDJ47K8FVJ126QTTXMGHD/Budgie)](https://api.gh-polls.com/poll/01F3HZDJ47K8FVJ126QTTXMGHD/Budgie/vote)
[![](https://api.gh-polls.com/poll/01F3HZDJ47K8FVJ126QTTXMGHD/Cinnamon)](https://api.gh-polls.com/poll/01F3HZDJ47K8FVJ126QTTXMGHD/Cinnamon/vote)
[![](https://api.gh-polls.com/poll/01F3HZDJ47K8FVJ126QTTXMGHD/Enlightenment)](https://api.gh-polls.com/poll/01F3HZDJ47K8FVJ126QTTXMGHD/Enlightenment/vote)
[![](https://api.gh-polls.com/poll/01F3HZDJ47K8FVJ126QTTXMGHD/Window%20Manager%20(aktuell%20Awesome%20oder%20Sway))](https://api.gh-polls.com/poll/01F3HZDJ47K8FVJ126QTTXMGHD/Window%20Manager%20(aktuell%20Awesome%20oder%20Sway)/vote)

**Comment by Malternative3772** [comment]
Ja geil funktioniert nicht

**Comment by DasPrombelBread** [comment]
**Ergebnis der Umfrage:**
**KDE und XFCE** sind fast gleichauf, somit wird es, wenn möglich, beide Desktops in unserer Distro geben, als erstes aber vermutlich XFCE, da dies einen Punkt vorsprung hat. (KDE: 13, XFCE: 14)

**Comment by Juliaaan2502** [comment]
> 
> 
> **Ergebnis der Umfrage:**
> **KDE und XFCE** sind fast gleichauf, somit wird es, wenn möglich, beide Desktops in unserer Distro geben, als erstes aber vermutlich XFCE, da dies einen Punkt vorsprung hat. (KDE: 13, XFCE: 14)

cool, ne' cinnamon version hätt ich mehr gefeiert! Wenn LGOS kommt nehm ich eh die XFCE, KDE hängt mir zum Halse raus 🙄

**Comment by Malternative3772** [comment]
Na ja Cinnamon ist auf Platz 3. Wir können uns ja überlegen ne Cinnamon Version zu erstellen wenn wir alles andere fertig haben
